name: CI/CD

on:
  push:
  pull_request:
    branches:
      - '*'

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Build Docker image
        run: docker build -t scholar-sync .

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: $VERCEL_TOKEN
          vercel-args: '--prod'